### ISSUE TITLE
Add countdown timer

### ISSUE THREAD

**Issue by ErikBoesen** [ComethruApp/comethruapp.github.io#5]
Black out the whole screen and superimpose a countdown timer to our release at the start of January 8th, 2020.

I once made something like this for my robotics team back in HS; you can steal code from these files:
https://github.com/frc1418/frc1418.github.io/blob/2ec4c26803a25134673a6cee482bf06a49e80b11/_pages/countdown.html
https://github.com/frc1418/frc1418.github.io/blob/4f7d0165a7d137fd4d38be2b063bb7fd51954037/js/countdown.js
https://github.com/frc1418/frc1418.github.io/blob/master/css/countdown.sass (this is in SASS so you'll need to compile it which is easy online)

**Comment by AAgar** [comment]
1. Separate page that is just a countdown which we change once the app is ready
2. Separate page with a countdown that redirects to the landing/download page
3. Current page but use js/jquery to hide the content and display a countdown timer until Jan 8

Which one should I do?

**Comment by AAgar** [comment]
As for #3, it could alter the CSS based on the date so that the current content is hidden until the specified date and the countdown timer is shown.

Just one idea; there are tons of other ways.

**Comment by ErikBoesen** [comment]
Just did this on my own during a particularly uninteresting CPSC 201 lecture
